name: lint_test_deploy_on_push
on: 
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses:  actions/checkout@v3
      - name: install nodejs-v18
        uses: actions@setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
        
      - name: lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: npm test
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "Deploying.."

